/*     */ package com.landov.budgiegenex;
/*     */ 
/*     */ import java.awt.Component;
/*     */ import java.awt.Dimension;
/*     */ import java.awt.GridBagConstraints;
/*     */ import java.awt.GridBagLayout;
/*     */ import javax.swing.ButtonGroup;
/*     */ import javax.swing.JApplet;
/*     */ import javax.swing.JLabel;
/*     */ import javax.swing.JPanel;
/*     */ import javax.swing.JRadioButton;
/*     */ 
/*     */ public class ControlPanel
/*     */   extends JPanel {
/*1     */   private JRadioButton B1;
/*2     */   private JRadioButton B2;
/*3     */   private JRadioButton b11;
/*4     */   private JRadioButton b12;
/*5     */   private JRadioButton b21;
/*6     */   private JRadioButton b22;
/*7     */   private JRadioButton by21;
/*8     */   private JRadioButton by22;
/*9     */   private JRadioButton bg1;
/*10     */   private JRadioButton bg2;
/*11     */   private JRadioButton C1;
/* 12    */   private JRadioButton C2;
/*  13   */   private JRadioButton cg1;
/*14     */   private JRadioButton cg2;
/*15     */   private JRadioButton cw1;
/*     */   private JRadioButton cw2;
/*     */   private JRadioButton cd1;
/*     */   private JRadioButton cd2;
/*     */   private JRadioButton D1;
/*     */   private JRadioButton D2;
/*     */   private JRadioButton d1;
/*     */   private JRadioButton d2;
/*     */   private JRadioButton V1;
/*     */   private JRadioButton V2;
/*     */   private JRadioButton v1;
/*     */   private JRadioButton v2;
/*     */   private JRadioButton S1;
/*     */   private JRadioButton S2;
/*     */   private JRadioButton s1;
/*     */   private JRadioButton s2;
/*     */   private JRadioButton T1;
/*     */   private JRadioButton T2;
/*     */   private JRadioButton t1;
/*     */   private JRadioButton t2;
/*     */   private JRadioButton W;
/*     */   private JRadioButton Z1;
/*     */   private JRadioButton Z2;
/*     */   private JRadioButton Zcin1;
/*     */   private JRadioButton Zcin2;
/*     */   private JRadioButton Zino1;
/*     */   private JRadioButton Zino2;
/*     */   private JRadioButton Zcino1;
/*     */   private JRadioButton Zcino2;
/*     */   private JRadioButton Zop1;
/*     */   private JRadioButton Zop2;
/*     */   private ButtonGroup ZW1Group;
/*     */   private ButtonGroup ZW2Group;
/*     */   private ButtonGroup b1Group;
/*     */   private ButtonGroup b2Group;
/*     */   private ButtonGroup C1Group;
/*     */   private ButtonGroup C2Group;
/*     */   private ButtonGroup D1Group;
/*     */   private ButtonGroup D2Group;
/*     */   private ButtonGroup V1Group;
/*     */   private ButtonGroup V2Group;
/*     */   private ButtonGroup S1Group;
/*     */   private ButtonGroup S2Group;
/*     */   private ButtonGroup T1Group;
/*     */   private ButtonGroup T2Group;
/*     */   public BudgiePanel budgiePanel;
/*     */   public JApplet myApplet;
/*  76 */   private GridBagLayout layout = new GridBagLayout();
/*     */   private GridBagConstraints constraints;
/*     */   
/*     */   private void addComponent(Component component, int row, int column, int width, int height) {
/*  80 */     this.constraints.gridx = column;
/*  81 */     this.constraints.gridy = row;
/*  82 */     this.constraints.gridwidth = width;
/*  83 */     this.constraints.gridheight = height;
/*  84 */     this.layout.setConstraints(component, this.constraints);
/*  85 */     add(component);
/*     */   }
/*     */   
/*     */   public ControlPanel() {
/*  89 */     setLayout(this.layout);
/*  90 */     this.constraints = new GridBagConstraints();
/*  91 */     this.constraints.fill = 0;
/*  92 */     this.constraints.weightx = 0.0D;
/*  93 */     this.constraints.weighty = 0.0D;
/*  94 */     this.constraints.anchor = 17;
/*  95 */     setMaximumSize(new Dimension(100, 640));
/*  96 */     BButtonHandler bButtonHandler = new BButtonHandler(this);
/*  97 */     this.B1 = new JRadioButton("B", true);
/*  98 */     this.B2 = new JRadioButton("B - normal gene", true);
/*  99 */     this.b11 = new JRadioButton("b1");
/* 100 */     this.b12 = new JRadioButton("b1 - type one blue mutation");
/* 101 */     this.b21 = new JRadioButton("b2");
/* 102 */     this.b22 = new JRadioButton("b2 - type two blue mutation");
/* 103 */     this.by21 = new JRadioButton("by2");
/* 104 */     this.by22 = new JRadioButton("by2 - yellowface type two mutation");
/* 105 */     this.bg1 = new JRadioButton("bg");
/* 106 */     this.bg2 = new JRadioButton("bg - goldenface mutation");
/* 107 */     this.b1Group = new ButtonGroup();
/* 108 */     this.b1Group.add(this.B1);
/* 109 */     this.b1Group.add(this.b11);
/* 110 */     this.b1Group.add(this.b21);
/* 111 */     this.b1Group.add(this.by21);
/* 112 */     this.b1Group.add(this.bg1);
/* 113 */     this.b2Group = new ButtonGroup();
/* 114 */     this.b2Group.add(this.B2);
/* 115 */     this.b2Group.add(this.b12);
/* 116 */     this.b2Group.add(this.b22);
/* 117 */     this.b2Group.add(this.by22);
/* 118 */     this.b2Group.add(this.bg2);
/* 119 */     this.B1.addItemListener(bButtonHandler);
/* 120 */     this.B2.addItemListener(bButtonHandler);
/* 121 */     this.b11.addItemListener(bButtonHandler);
/* 122 */     this.b12.addItemListener(bButtonHandler);
/* 123 */     this.b21.addItemListener(bButtonHandler);
/* 124 */     this.b22.addItemListener(bButtonHandler);
/* 125 */     this.by21.addItemListener(bButtonHandler);
/* 126 */     this.by22.addItemListener(bButtonHandler);
/* 127 */     this.bg1.addItemListener(bButtonHandler);
/* 128 */     this.bg2.addItemListener(bButtonHandler);
/* 129 */     this.C1 = new JRadioButton("C", true);
/* 130 */     this.C2 = new JRadioButton("C - normal gene", true);
/* 131 */     this.cg1 = new JRadioButton("cg");
/* 132 */     this.cg2 = new JRadioButton("cg - greywing mutation");
/* 133 */     this.cw1 = new JRadioButton("cw");
/* 134 */     this.cw2 = new JRadioButton("cw - clearwing mutation");
/* 135 */     this.cd1 = new JRadioButton("cd");
/* 136 */     this.cd2 = new JRadioButton("cd - dilute mutation");
/* 137 */     this.C1Group = new ButtonGroup();
/* 138 */     this.C1Group.add(this.C1);
/* 139 */     this.C1Group.add(this.cg1);
/* 140 */     this.C1Group.add(this.cw1);
/* 141 */     this.C1Group.add(this.cd1);
/* 142 */     this.C2Group = new ButtonGroup();
/* 143 */     this.C2Group.add(this.C2);
/* 144 */     this.C2Group.add(this.cg2);
/* 145 */     this.C2Group.add(this.cw2);
/* 146 */     this.C2Group.add(this.cd2);
/* 147 */     this.C1.addItemListener(bButtonHandler);
/* 148 */     this.C2.addItemListener(bButtonHandler);
/* 149 */     this.cg1.addItemListener(bButtonHandler);
/* 150 */     this.cg2.addItemListener(bButtonHandler);
/* 151 */     this.cw1.addItemListener(bButtonHandler);
/* 152 */     this.cw2.addItemListener(bButtonHandler);
/* 153 */     this.cd1.addItemListener(bButtonHandler);
/* 154 */     this.cd2.addItemListener(bButtonHandler);
/* 155 */     this.D1 = new JRadioButton("D", true);
/* 156 */     this.D2 = new JRadioButton("D - normal gene", true);
/* 157 */     this.d1 = new JRadioButton("d");
/* 158 */     this.d2 = new JRadioButton("d - dark faktor mutation");
/* 159 */     this.D1Group = new ButtonGroup();
/* 160 */     this.D1Group.add(this.D1);
/* 161 */     this.D1Group.add(this.d1);
/* 162 */     this.D2Group = new ButtonGroup();
/* 163 */     this.D2Group.add(this.D2);
/* 164 */     this.D2Group.add(this.d2);
/* 165 */     this.D1.addItemListener(bButtonHandler);
/* 166 */     this.D2.addItemListener(bButtonHandler);
/* 167 */     this.d1.addItemListener(bButtonHandler);
/* 168 */     this.d2.addItemListener(bButtonHandler);
/* 169 */     this.V1 = new JRadioButton("V", true);
/* 170 */     this.V2 = new JRadioButton("V - normal gene", true);
/* 171 */     this.v1 = new JRadioButton("v");
/* 172 */     this.v2 = new JRadioButton("v - violet faktor mutation");
/* 173 */     this.V1Group = new ButtonGroup();
/* 174 */     this.V1Group.add(this.V1);
/* 175 */     this.V1Group.add(this.v1);
/* 176 */     this.V2Group = new ButtonGroup();
/* 177 */     this.V2Group.add(this.V2);
/* 178 */     this.V2Group.add(this.v2);
/* 179 */     this.V1.addItemListener(bButtonHandler);
/* 180 */     this.V2.addItemListener(bButtonHandler);
/* 181 */     this.v1.addItemListener(bButtonHandler);
/* 182 */     this.v2.addItemListener(bButtonHandler);
/* 183 */     this.S1 = new JRadioButton("S", true);
/* 184 */     this.S2 = new JRadioButton("S - normal gene", true);
/* 185 */     this.s1 = new JRadioButton("s");
/* 186 */     this.s2 = new JRadioButton("s - spangle mutation");
/* 187 */     this.S1Group = new ButtonGroup();
/* 188 */     this.S1Group.add(this.S1);
/* 189 */     this.S1Group.add(this.s1);
/* 190 */     this.S2Group = new ButtonGroup();
/* 191 */     this.S2Group.add(this.S2);
/* 192 */     this.S2Group.add(this.s2);
/* 193 */     this.S1.addItemListener(bButtonHandler);
/* 194 */     this.S2.addItemListener(bButtonHandler);
/* 195 */     this.s1.addItemListener(bButtonHandler);
/* 196 */     this.s2.addItemListener(bButtonHandler);
/* 197 */     this.T1 = new JRadioButton("T", true);
/* 198 */     this.T2 = new JRadioButton("T - normal gene", true);
/* 199 */     this.t1 = new JRadioButton("t");
/* 200 */     this.t2 = new JRadioButton("t - dominant pied mutation");
/* 201 */     this.T1Group = new ButtonGroup();
/* 202 */     this.T1Group.add(this.T1);
/* 203 */     this.T1Group.add(this.t1);
/* 204 */     this.T2Group = new ButtonGroup();
/* 205 */     this.T2Group.add(this.T2);
/* 206 */     this.T2Group.add(this.t2);
/* 207 */     this.T1.addItemListener(bButtonHandler);
/* 208 */     this.T2.addItemListener(bButtonHandler);
/* 209 */     this.t1.addItemListener(bButtonHandler);
/* 210 */     this.t2.addItemListener(bButtonHandler);
/* 211 */     this.W = new JRadioButton("W", true);
/* 212 */     this.Z1 = new JRadioButton("Z");
/* 213 */     this.Z2 = new JRadioButton("Z - sex chromosome", true);
/* 214 */     this.Zcin1 = new JRadioButton("Zcin");
/* 215 */     this.Zcin2 = new JRadioButton("Zcin - cinamon mutation");
/* 216 */     this.Zino1 = new JRadioButton("Zino");
/* 217 */     this.Zino2 = new JRadioButton("Zino - lutino/albino mutation");
/* 218 */     this.Zop1 = new JRadioButton("Zop");
/* 219 */     this.Zop2 = new JRadioButton("Zop - opaline mutation");
/* 220 */     this.Zcino1 = new JRadioButton("Zcin,ino");
/* 221 */     this.Zcino2 = new JRadioButton("Zcin,ino - cinamon-ino rare mutation");
/* 222 */     this.ZW1Group = new ButtonGroup();
/* 223 */     this.ZW1Group.add(this.W);
/* 224 */     this.ZW1Group.add(this.Z1);
/* 225 */     this.ZW1Group.add(this.Zcin1);
/* 226 */     this.ZW1Group.add(this.Zino1);
/* 227 */     this.ZW1Group.add(this.Zop1);
/* 228 */     this.ZW1Group.add(this.Zcino1);
/* 229 */     this.ZW2Group = new ButtonGroup();
/* 230 */     this.ZW2Group.add(this.Z2);
/* 231 */     this.ZW2Group.add(this.Zcin2);
/* 232 */     this.ZW2Group.add(this.Zino2);
/* 233 */     this.ZW2Group.add(this.Zop2);
/* 234 */     this.ZW2Group.add(this.Zcino2);
/* 235 */     this.W.addItemListener(bButtonHandler);
/* 236 */     this.Z1.addItemListener(bButtonHandler);
/* 237 */     this.Z2.addItemListener(bButtonHandler);
/* 238 */     this.Zcin1.addItemListener(bButtonHandler);
/* 239 */     this.Zcin2.addItemListener(bButtonHandler);
/* 240 */     this.Zino1.addItemListener(bButtonHandler);
/* 241 */     this.Zino2.addItemListener(bButtonHandler);
/* 242 */     this.Zop1.addItemListener(bButtonHandler);
/* 243 */     this.Zop2.addItemListener(bButtonHandler);
/* 244 */     this.Zcino1.addItemListener(bButtonHandler);
/* 245 */     this.Zcino2.addItemListener(bButtonHandler);
/* 246 */     addComponent(new JLabel("Blue mutations:"), 0, 0, 2, 1);
/* 247 */     addComponent(this.B1, 1, 0, 1, 1);
/* 248 */     addComponent(this.B2, 1, 1, 1, 1);
/* 249 */     addComponent(this.b11, 2, 0, 1, 1);
/* 250 */     addComponent(this.b12, 2, 1, 1, 1);
/* 251 */     addComponent(this.b21, 3, 0, 1, 1);
/* 252 */     addComponent(this.b22, 3, 1, 1, 1);
/* 253 */     addComponent(this.by21, 4, 0, 1, 1);
/* 254 */     addComponent(this.by22, 4, 1, 1, 1);
/* 255 */     addComponent(this.bg1, 5, 0, 1, 1);
/* 256 */     addComponent(this.bg2, 5, 1, 1, 1);
/* 257 */     addComponent(new JLabel("Dilution:"), 6, 0, 2, 1);
/* 258 */     addComponent(this.C1, 7, 0, 1, 1);
/* 259 */     addComponent(this.C2, 7, 1, 1, 1);
/* 260 */     addComponent(this.cg1, 8, 0, 1, 1);
/* 261 */     addComponent(this.cg2, 8, 1, 1, 1);
/* 262 */     addComponent(this.cw1, 9, 0, 1, 1);
/* 263 */     addComponent(this.cw2, 9, 1, 1, 1);
/* 264 */     addComponent(this.cd1, 10, 0, 1, 1);
/* 265 */     addComponent(this.cd2, 10, 1, 1, 1);
/* 266 */     addComponent(new JLabel("Dark factor:"), 11, 0, 2, 1);
/* 267 */     addComponent(this.D1, 12, 0, 1, 1);
/* 268 */     addComponent(this.D2, 12, 1, 1, 1);
/* 269 */     addComponent(this.d1, 13, 0, 1, 1);
/* 270 */     addComponent(this.d2, 13, 1, 1, 1);
/* 271 */     addComponent(new JLabel("Violet factor:"), 14, 0, 2, 1);
/* 272 */     addComponent(this.V1, 15, 0, 1, 1);
/* 273 */     addComponent(this.V2, 15, 1, 1, 1);
/* 274 */     addComponent(this.v1, 16, 0, 1, 1);
/* 275 */     addComponent(this.v2, 16, 1, 1, 1);
/* 276 */     addComponent(new JLabel("Spangle:"), 17, 0, 2, 1);
/* 277 */     addComponent(this.S1, 18, 0, 1, 1);
/* 278 */     addComponent(this.S2, 18, 1, 1, 1);
/* 279 */     addComponent(this.s1, 19, 0, 1, 1);
/* 280 */     addComponent(this.s2, 19, 1, 1, 1);
/* 281 */     addComponent(new JLabel("Dominant pied:"), 20, 0, 2, 1);
/* 282 */     addComponent(this.T1, 21, 0, 1, 1);
/* 283 */     addComponent(this.T2, 21, 1, 1, 1);
/* 284 */     addComponent(this.t1, 22, 0, 1, 1);
/* 285 */     addComponent(this.t2, 22, 1, 1, 1);
/* 286 */     addComponent(new JLabel("Sex chromosomes:"), 23, 0, 2, 1);
/* 287 */     addComponent(this.W, 24, 0, 1, 1);
/* 288 */     addComponent(this.Z2, 24, 1, 1, 1);
/* 289 */     addComponent(this.Z1, 25, 0, 1, 1);
/* 290 */     addComponent(this.Zcin1, 26, 0, 1, 1);
/* 291 */     addComponent(this.Zcin2, 26, 1, 1, 1);
/* 292 */     addComponent(this.Zino1, 27, 0, 1, 1);
/* 293 */     addComponent(this.Zino2, 27, 1, 1, 1);
/* 294 */     addComponent(this.Zop1, 28, 0, 1, 1);
/* 295 */     addComponent(this.Zop2, 28, 1, 1, 1);
/* 296 */     addComponent(this.Zcino1, 29, 0, 1, 1);
/* 297 */     addComponent(this.Zcino2, 29, 1, 1, 1);
/*     */   }
/*     */ }



